FROM carcel/image_name:php-5.6

USER root

RUN php5enmod xdebug && \
    echo "xdebug.idekey = PHPSTORM" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.default_enable = 0" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.remote_enable = 1" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.remote_autostart = 0" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.remote_connect_back = 0" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.profiler_enable = 0" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.max_nesting_level = 500" >> /etc/php5/apache2/conf.d/20-xdebug.ini && \
    echo "xdebug.remote_host = 10.254.254.254" >> /etc/php5/apache2/conf.d/20-xdebug.ini

USER docker